### ISSUE TITLE
Support arbitrary categories

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/iitc.modos189.ru#1]
Currently only predefined categories supported: https://github.com/IITC-CE/iitc.modos189.ru/blob/5d0df1f37b368026d637f83004244b2907eb44bd/update.py#L34

- If some plugin has not defined category - it goes to `Misc | Unclassified plugins`.
- If there is no plugins in some category - it is shown anyway (empty).

Examples now at https://iitc.modos189.ru/test_builds.html

**Comment by johnd0e** [comment]
It would be better if categories list was dynamically gathered from processed files.
- Show new categories w/o description
- Do not show empty categories

**Comment by modos189** [comment]
> Show new categories w/o description

I like decision not to get rid of the Misc category, but to create new categories as needed

**Comment by johnd0e** [comment]
> I like decision not to get rid of the Misc category

I never proposed get rid of Misc.
There are some plugins with @category set to `Misc`.
Also any uncategorized plugins also go there.

> but to create new categories as needed

Do you mean automatically or manual way?

**Comment by modos189** [comment]
Manual. In addition, this will motivate to create a description)

**Comment by johnd0e** [comment]
> Manual.

Sure, we always can do it manual, but i do not think that it's hard to do it automatically.

Thing I do not like most: if we get some plugin with misspelled category - it silently goes to `Misc`.
And it may stay unnoticed for long time.

>  In addition, this will motivate to create a description)

Empty description field is enough motivation for me)

**Comment by modos189** [comment]
Added support undefined categories

https://github.com/IITC-CE/iitc.modos189.ru/commit/9a146edaad9afd257b71ccab4811056f145a6d7b
