### ISSUE TITLE
Choosing recommended userscript manager 

### ISSUE THREAD

**Issue by modos189** [IITC-CE/iitc.modos189.ru#10]
We now [recommend](https://iitc.modos189.ru/download_desktop.html) using GreaseMonkey for Firefox and TamperMonkey for Chrome.

The problem is that TamperMonkey is distributed under a proprietary license, and GreaseMonkey exists only for Firefox.

It would be great if we added a third userscript manager to user's choice, which would be Free (as in Freedom) and run under Chrome or Chrome and Firefox.

Can you recommend a good candidate for these conditions?

**Comment by johnd0e** [comment]
https://violentmonkey.github.io/
and iitc-button
