### ISSUE TITLE
Ids (anchors) for plugins and sections

### ISSUE THREAD

**Issue by Eccenux** [IITC-CE/iitc.modos189.ru#7]
For iitc.me you can create links to any plugin. For example if the the is `distance-to-portal` then the anchor is `#plugin-distance-to-portal`.

Would be nice to also provide those links in the table (make them more discoverable). So better then on iitc.me make plugin id a link to the plugins anchor.

And while you are at it you could make links to sections (main download, cache, controls, draw etc).

**Comment by modos189** [comment]
Done. See https://iitc.modos189.ru/download_desktop.html#iitc-plugin-scale-bar@breunigs
